server:
  port: ${CUSTOM.SERVER.PORT:9090}

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
    fetchRegistry: true

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            - MitocodeFilter=MitocodeKey, MitocodeValue
            
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            # - AddRequestParameter=tokens,mitocode
            # - AddRequestHeader=token,mitocode
            # - AddResponseHeader=CUSTOM_RESPONSE_HEADER,HEADER_Mitocode
            # Forma 2 ver CustomFilter.java
            - MitocodeFilter=MitocodeKey, MitocodeValue
            # Forma 1 ver CustomFilter.java
            # - name: CustomFilter
            #   args:
            #     headerKey: MitocodeKey
            #     headerValue: MitocodeValue
