server:
 porto: ${CUSTOM.SERVER.PORT:9004}
 
eureka:
 client:
  register-with-eureka: true
  service-url:
   defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
   
   
### Mongo database configuration
spring:
 data:
  mongodb:
   host: localhost
   port: 27017
   database: mitocode
   # username: '{cipher}15dfd68adfe32e63d2ef16b7e'
   # password: '{cipher}15dfd68adfe32e63d2ef16b7e'
   uri: mongodb://mitocode:mitocode@localhost:27017
   authentication-database: admin